@startuml


left to right direction

actor "창고관리자" as wh_manager
actor "총관리자" as admin

actor "회원" as user
actor "배송기사" as delivery
actor "비회원"
rectangle "고객센터"{
admin-->(공지사항 등록)


(공지사항 등록)<|--(공지사항 조회)
(공지사항 등록)<|--(공지사항 수정)
(공지사항 등록)<|--(공지사항 삭제)



wh_manager--up->(공지사항 조회)
user-up-->(공지사항 조회)
delivery-up-->(공지사항 조회)
'admin-->(공지사항 조회)
'admin-->(공지사항 수정)
'admin-->(공지사항 삭제)

user-->(1:1게시판 작성)
admin-->(1:1게시판 작성)

(문의글 작성)<--user
(문의글 작성)<--비회원

(문의게시판 조회)--|>(문의글 작성)
(문의글 수정)--|>(문의글 작성)
(문의글 삭제)--|>(문의글 작성)

admin-down->(문의게시판 조회)
wh_manager-down->(문의게시판 조회)
delivery-down->(문의게시판 조회)
'user->(문의게시판 조회)
'비회원->(문의게시판 조회)

admin-->(문의글 수정)
'user-->(문의글 수정)
'비회원-->(문의글 수정)

admin-->(문의글 삭제)
'user-->(문의글 삭제)
'비회원-->(문의글 삭제)


}
@enduml