@startuml

left to right direction

actor "창고관리자" as wh_m
actor "총관리자" as admin

rectangle "재무관리"{
wh_m--> (지출 및 매출 내역 등록)
admin--> (지출 및 매출 내역 등록)

(총정산내역 조회)-up-|>(지출 및 매출 내역 등록)

(총정산내역 조회)..>(지출내역 조회):<<extends>>
(지출내역 조회)..>(연간지출내역 조회):<<extends>>
(지출내역 수정)-up-|>(지출 및 매출 내역 등록)
(지출내역 삭제)-up-|>(지출 및 매출 내역 등록)



}
@enduml