@startuml
rectangle "창고관리"{
left to right direction

actor "창고관리자" as wh_manager
actor "총관리자" as admin

admin -->(창고 등록)
admin -->(창고 조회)

(창고 조회)-up-|>(창고 등록)
(창고현황 리스트)-up-|>(창고 등록)

admin -->(창고현황 리스트)
wh_manager -->(창고현황 리스트)

wh_manager-->(창고 조회)

(창고 조회)..>(소재지별 창고조회):<<extends>>
(창고 조회)..>(창고명별 창고조회):<<extends>>
(창고 조회)..>(창고종류별 창고조회):<<extends>>

}
@enduml