@startuml

left to right direction

package "관리자"{
actor "창고관리자" as wh_manager
actor "총관리자" as admin
}
actor "회원" as user


rectangle "재고관리"{

wh_manager-right-|>admin
관리자--(재고실사 등록)


(재고실사 조회)<..(재고실사 삭제):<<extend>>
(재고실사 조회)<..(재고실사 수정):<<extend>>
관리자--(재고실사 조회)
관리자--(재고 조회)

(재고 조회)<..(대분류별 조회):<<include>>


user-up-(재고 조회)
user-up-(품목현황 리스트)


user-up--(대분류별 조회)
(대분류별 조회)<..(중분류별 조회):<<extend>>
(중분류별 조회)<..(소분류별 조회):<<extend>>

관리자--(품목현황 리스트)
관리자--(창고현황 리스트)
관리자--(거래처현황 리스트)


}
@enduml

